<a href="https://colab.research.google.com/github/FSRData/Americanas_PoloTech_Modulo3/blob/main/Americanas_PoloTech_%7C_M%C3%B3dulo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Americanas - PoloTech** | Módulo 3 | Aula 2 - NUMPY

##### Arrays diferentemente de listas permitem apenas um tipo de dado.
##### Cnsomem menos memória e agilizam o processamento dos dados.

#### Importação da Biblioteca Numpy

In [2]:
import numpy as np

#### Metodo para transformação de lista em array

In [69]:
lista = [1, 2, 3, 4, 5]

In [70]:
lista

[1, 2, 3, 4, 5]

In [71]:
array = np.array(lista)

In [72]:
array

array([1, 2, 3, 4, 5])

#### Metodo para inicialização de array com tamanho definido


In [11]:
# Preenchido com zero
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# Preenchido com um
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Criando array com a função range

In [14]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.array(list(range(3, 10, 2)))

array([3, 5, 7, 9])

#### Usando método .arange()
###### Análogo a função range()

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

#### Método .linspace()
###### Cria um vetor com elementos ditribuídos igualitáriamente dentro do range especificado

In [19]:
arr = np.linspace(35, 100, 20)
arr

array([ 35.        ,  38.42105263,  41.84210526,  45.26315789,
        48.68421053,  52.10526316,  55.52631579,  58.94736842,
        62.36842105,  65.78947368,  69.21052632,  72.63157895,
        76.05263158,  79.47368421,  82.89473684,  86.31578947,
        89.73684211,  93.15789474,  96.57894737, 100.        ])

#### Método .randon()
###### Gera arrays com vetores de números aleatórios

In [20]:
# Método random.rand()
# Gera números aleatórios com a mesma probabilidade de qualquer outro número dentro do range
np.random.rand(10)

array([0.92151019, 0.70614185, 0.69876653, 0.58801736, 0.97649034,
       0.08933779, 0.42641474, 0.56354566, 0.42864241, 0.25134294])

In [21]:
# Método random.randint()
# Gera números inteiros dentro do intervalo especificado
# random.randint(x, y, z) onde:
# x -> Ínicio
# y -> Fim
# z -> Passo
np.random.randint(0, 100, 10)

array([77, 43, 54, 25,  3,  7, 19, 43, 84, 52])

In [24]:
# O método random.normal() gera números com maior probabilidade de estar dentro do valor médio da amostragem
# random.normal(x, y, z) onde:
# x -> Média
# y -> Desvio padrão
# z -> Qtde de números
np.random.normal(2, 1, 3)

array([1.95425491, 0.46881929, 1.4997914 ])

#### Indexação

In [26]:
arr = np.arange(2, 50, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [27]:
# Acessar um elemento individual:
arr[2]

8

In [29]:
# Acessando com índice negativo
arr[-4]

38

In [30]:
# Slcing em arrays
arr[2:5]

array([ 8, 11, 14])

In [31]:
# Slicing sem indicar o inicio
arr[:5]

array([ 2,  5,  8, 11, 14])

In [32]:
# Slicing sem indicar o final
arr[-4:]

array([38, 41, 44, 47])

#### Oeprações matemáticas simples
###### São feitas elementos a elementos

In [33]:
arr * 2 

array([ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94])

In [34]:
arr + 2

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [35]:
arr ** 2

array([   4,   25,   64,  121,  196,  289,  400,  529,  676,  841, 1024,
       1225, 1444, 1681, 1936, 2209])

In [38]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [39]:
arr1 + arr2

array([5, 7, 9])

In [40]:
arr1 * arr2

array([ 4, 10, 18])

In [41]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

#### Métodos Úteis

In [58]:
# random.seed() fixa o resuldado do gerador de números aleatórios
# Pode se apresentar como random_state

np.random.seed(10)
rand = np.random.randint(0, 10, 5)
rand

array([9, 4, 0, 1, 9])

In [59]:
# Método para valor máximo
rand.max()

9

In [60]:
# Método para valor mínimo
rand.min()

0

In [61]:
# Método para posição valor máximo
rand.argmax()

0

In [62]:
# Método para posição valor minimo
rand.argmin()

2

In [64]:
# Somar todos os valores
rand.sum()

23

In [63]:
# Média de todos os valores
rand.mean()

4.6

#### Desvio Padrão dos valores

In [65]:
rand.std()

3.826225293941798

#### Ordenar os valores do array

In [66]:
rand.sort()
rand

array([0, 1, 4, 9, 9])

#### Alterar o tipo de dado

In [67]:
rand.astype(float)

array([0., 1., 4., 9., 9.])

#### Exercícios

#### **Exercício 1**

##### Escreva uma função que receba dois argumentos: um número qualquer de arrays (de mesmo tamanho) em numpy; e o número de elementos de cada array. A função deve retornar um escalar que representa a soma total de todos estes arrays. Inclua na função uma condição de verificação em que, caso haja um array de tamanho distinto dos demais, um erro seja retornado.

#### **Exercício 2**
##### Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.


#### **Exercício 3**
##### Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

#### **Exercício 4**
##### Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

### **Americanas - PoloTech** | Módulo 3 | Aula 3 - NUMPY